hInt = comm.ConvolutionalInterleaver('NumRegisters', 3, ...
                    'RegisterLengthStep', 2, ...
                    'InitialConditions', [ -1 -2 -3]');
    hDeInt = comm.ConvolutionalDeinterleaver('NumRegisters', 3, ...
                    'RegisterLengthStep', 2, ...
                    'InitialConditions', [-1 -2 -3]');
    data = (0:20)';
    intrlvData = step(hInt, data);
    deintrlvData = step(hDeInt, intrlvData);
    % compare the original sequence, interleaved sequence and restored sequence.
    [data, intrlvData, deintrlvData]